"""add phone column and fix roles JSON type

Revision ID: 04048a6f2071
Revises: c53fe206ebe0
Create Date: 2025-08-24 15:08:08.147972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04048a6f2071'
down_revision: Union[str, Sequence[str], None] = 'c53fe206ebe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
