"""create users, wallets, otps tables

Revision ID: 54fb38208aaa
Revises: 43fee7cf8ddd
Create Date: 2025-08-25 11:56:10.974463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54fb38208aaa'
down_revision: Union[str, Sequence[str], None] = '43fee7cf8ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
